# Generated by Django 4.2.16 on 2024-10-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mortuary_staff", "0002_initial"),
        ("mortuary_staff", "0002_mortuarystaff_user"),
    ]

    operations = []
