# Generated by Django 4.2 on 2024-09-18 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoliceOfficer",
            fields=[
                ("officer_id", models.AutoField(primary_key=True, serialize=False)),
                ("rank", models.CharField(max_length=30)),
                ("contact", models.CharField(max_length=15)),
                ("generated_code", models.CharField(max_length=30)),
                (
                    "station_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stations.policestation",
                    ),
                ),
            ],
        ),
    ]
