# Generated by Django 4.2.16 on 2024-10-31 16:05

from django.db import migrations, models
import django.db.models.deletion
import unidentified_bodies.models


class Migration(migrations.Migration):

    dependencies = [
        ("mortuary_staff", "0003_merge_0002_initial_0002_mortuarystaff_user"),
        ("unidentified_bodies", "0003_alter_unidentifiedbody_reporting_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidentifiedbody",
            name="staff_id",
            field=models.ForeignKey(
                default=unidentified_bodies.models.get_default_staff,
                on_delete=django.db.models.deletion.CASCADE,
                to="mortuary_staff.mortuarystaff",
            ),
        ),
    ]
