# Generated by Django 4.2.16 on 2024-10-26 07:57

from django.db import migrations, models
import missing_persons.models


class Migration(migrations.Migration):

    dependencies = [
        ("missing_persons", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="missingperson",
            name="status",
            field=models.CharField(
                choices=[
                    ("missing", "Missing"),
                    ("found", "Found"),
                    ("departed", "Departed"),
                ],
                default="missing",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="missingperson",
            name="contact",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="missingperson",
            name="eye_color",
            field=models.CharField(
                choices=[("black", "Black"), ("brown", "Brown")],
                default="black",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="missingperson",
            name="first_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="missingperson",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="missingperson",
            name="hair_color",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="missingperson",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="missingperson",
            name="image",
            field=models.ImageField(
                upload_to="missing_persons_images/",
                validators=[missing_persons.models.validate_image_format],
            ),
        ),
        migrations.AlterField(
            model_name="missingperson",
            name="last_name",
            field=models.CharField(default="Unknown", max_length=20),
        ),
        migrations.AlterField(
            model_name="missingperson",
            name="location",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="missingperson",
            name="skin_color",
            field=models.CharField(
                choices=[
                    ("light_skinned", "Light Skinned"),
                    ("dark_skinned", "Dark Skinned"),
                ],
                default="dark_skinned",
                max_length=20,
            ),
        ),
    ]
