# Generated by Django 4.2.16 on 2024-09-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missing_persons", "0003_alter_missingperson_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="missingperson",
            name="status",
            field=models.CharField(
                choices=[
                    ("missing", "Missing"),
                    ("found", "Found"),
                    ("departed", "Departed"),
                ],
                default="Missing",
                max_length=50,
            ),
        ),
    ]
