# Generated by Django 4.2.16 on 2024-09-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("missing_persons", "0004_missingperson_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="missingperson",
            name="status",
        ),
    ]
