# Generated by Django 4.2.16 on 2024-09-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missing_persons", "0005_remove_missingperson_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missingperson",
            name="image",
            field=models.ImageField(upload_to="missing_persons_images/"),
        ),
    ]
