# Generated by Django 4.2.16 on 2024-10-16 04:08

from django.db import migrations, models
import missing_persons.models


class Migration(migrations.Migration):

    dependencies = [
        ("missing_persons", "0007_alter_missingperson_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missingperson",
            name="image",
            field=models.ImageField(
                upload_to="missing_persons_images/",
                validators=[missing_persons.models.validate_image_format],
            ),
        ),
    ]
