# Generated by Django 4.2.16 on 2024-10-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("missing_persons", "0009_missingperson_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="missingperson",
            name="status",
        ),
    ]
