# Generated by Django 4.2.16 on 2024-10-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missing_persons", "0010_remove_missingperson_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="missingperson",
            name="status",
            field=models.CharField(
                choices=[
                    ("missing", "Missing"),
                    ("found", "Found"),
                    ("departed", "Departed"),
                ],
                default="missing",
                max_length=20,
            ),
        ),
    ]
