# Generated by Django 4.2.16 on 2024-10-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "missing_persons",
            "0003_missingperson_status_alter_missingperson_contact_and_more",
        ),
        ("missing_persons", "0011_missingperson_status"),
    ]

    operations = []
