# Generated by Django 4.2.16 on 2024-10-31 16:09

from django.db import migrations, models
import django.db.models.deletion
import missing_persons.models


class Migration(migrations.Migration):

    dependencies = [
        ("police", "0002_initial"),
        ("missing_persons", "0012_merge_20241026_1721"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missingperson",
            name="officer_id",
            field=models.ForeignKey(
                default=missing_persons.models.get_default_officer,
                on_delete=django.db.models.deletion.CASCADE,
                to="police.policeofficer",
            ),
        ),
    ]
