# Generated by Django 4.2.16 on 2024-11-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missing_persons", "0013_alter_missingperson_officer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missingperson",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("missing", "Missing"),
                    ("found", "Found"),
                    ("departed", "Departed"),
                ],
                default="missing",
                max_length=20,
            ),
        ),
    ]
